"""Team social feed — the visible surface of fan opinion (AFO plan Part D).

Two kinds of post land here:
  - **Manual**: general support or frustration about the club, chosen from a
    fixed catalog. No free text, so no moderation surface.
  - **Auto**: generated when a fan rates a player or votes on the GM, so an
    opinion they expressed elsewhere shows up in the feed in their voice.

Auto posts are a DISPLAY artifact of a vote that already counts as sentiment —
they never feed the model again, or every vote would count twice. Re-rating
replaces your previous auto post rather than stacking a contradiction.

The feed is ephemeral: posts age out at FEED_POST_TTL_HOURS.
"""

from datetime import datetime, timedelta
from typing import Dict, List, Optional

from sqlalchemy import func
from sqlalchemy.orm import Session

from database.models import TeamFeedPost
from constants import (
    FEED_POST_CATALOG, FEED_POST_TTL_HOURS,
    FEED_MAX_POSTS_PER_WINDOW, FEED_RATE_WINDOW_HOURS,
)


class FeedError(Exception):
    """Invalid post (unknown key, wrong target shape, rate-limited)."""


def catalogEntry(postKey: str):
    """(text, target, valence) for a catalog key, or None.

    Falls through to the GAME catalog so a post rendered out of the feed reads
    correctly whichever composer produced it.
    """
    return FEED_POST_CATALOG.get(postKey) or GAME_FEED_CATALOG.get(postKey)


def renderPost(postKey: str, targetName: Optional[str] = None) -> str:
    """The display text, with {name} filled in."""
    entry = catalogEntry(postKey)
    if not entry:
        return ''
    text = entry[0]
    if '{name}' in text:
        return text.replace('{name}', targetName or 'the GM')
    return text


class FeedRepository:
    def __init__(self, session: Session, now: Optional[datetime] = None):
        self.session = session
        # Injectable clock so decay/rate-limit behaviour is testable.
        self._now = now

    def now(self) -> datetime:
        return self._now or datetime.utcnow()

    # -------------------------------------------------------------- write

    def addPost(self, userId: int, teamId: int, postKey: str,
                targetPlayerId: Optional[int] = None,
                gameId: Optional[int] = None) -> TeamFeedPost:
        """Post a pre-made reaction. Raises FeedError on anything invalid.

        `gameId` scopes the post to one match — that is what keeps a shout at
        tonight's game out of tomorrow's stand.
        """
        isGamePost = postKey in GAME_FEED_CATALOG
        entry = catalogEntry(postKey)
        if entry is None:
            raise FeedError(f"unknown post '{postKey}'")
        _text, target, _valence = entry

        # A game line only exists in the context of a game, and a club line is
        # about the season — neither belongs in the other's composer.
        if isGamePost and gameId is None:
            raise FeedError("that post belongs to a game")
        if gameId is not None and not isGamePost:
            raise FeedError("that post is about the club, not this game")

        # Only general team posts are manually postable. Opinions about a
        # specific player or the GM arrive by rating / voting, which generates
        # the post for you — letting them be posted directly would double-count
        # and let one fan spam an opinion they can only hold once.
        if not isGamePost and target != 'team':
            raise FeedError("that post is generated by rating, not posted directly")
        if targetPlayerId:
            raise FeedError("general posts do not take a target")

        if self.remainingPosts(userId) <= 0:
            raise FeedError(
                f"post limit reached ({FEED_MAX_POSTS_PER_WINDOW} per "
                f"{FEED_RATE_WINDOW_HOURS}h) — give it a minute")

        post = TeamFeedPost(
            user_id=userId, team_id=teamId, post_key=postKey,
            target_type=target, target_player_id=targetPlayerId,
            game_id=gameId,
            created_at=self.now())
        self.session.add(post)
        return post

    def remainingPosts(self, userId: int) -> int:
        """Posts this fan has left in the current rate window."""
        since = self.now() - timedelta(hours=FEED_RATE_WINDOW_HOURS)
        used = (self.session.query(func.count(TeamFeedPost.id))
                .filter(TeamFeedPost.user_id == userId,
                        TeamFeedPost.created_at >= since,
                        # Auto posts don't count. They come from ratings, which
                        # are already net-one-per-target and self-limiting —
                        # charging them here would mean rating your roster
                        # locks you out of actually posting.
                        TeamFeedPost.is_auto == False)   # noqa: E712
                .scalar()) or 0
        return max(0, FEED_MAX_POSTS_PER_WINDOW - int(used))

    def purgeExpired(self) -> int:
        """Drop posts past their TTL. The feed is meant to be ephemeral, so
        this keeps the table from growing without bound."""
        cutoff = self.now() - timedelta(hours=FEED_POST_TTL_HOURS)
        n = (self.session.query(TeamFeedPost)
             .filter(TeamFeedPost.created_at < cutoff)
             .delete(synchronize_session=False))
        return int(n or 0)

    # --------------------------------------------------------------- read

    def _liveQuery(self):
        cutoff = self.now() - timedelta(hours=FEED_POST_TTL_HOURS)
        return self.session.query(TeamFeedPost).filter(
            TeamFeedPost.created_at >= cutoff)

    def getGameFeed(self, gameId: int, limit: int = 50) -> List[TeamFeedPost]:
        """Most recent live posts shouted AT one game, from either stand."""
        return (self._liveQuery()
                .filter(TeamFeedPost.game_id == gameId)
                .order_by(TeamFeedPost.created_at.desc())
                .limit(limit).all())

    def getFeed(self, teamId: int, limit: int = 50) -> List[TeamFeedPost]:
        """Most recent live posts for a team.

        ⚠️ Excludes game posts. A club's stand is about the club; a shout at one
        night's match would otherwise sit there for a day looking like an
        opinion about the season.
        """
        return (self._liveQuery()
                .filter(TeamFeedPost.team_id == teamId,
                        TeamFeedPost.game_id.is_(None))
                .order_by(TeamFeedPost.created_at.desc())
                .limit(limit).all())

    # ---------------------------------------------------------- auto posts

    def _clearAutoPost(self, userId: int, teamId: int, targetType: str,
                       targetPlayerId=None) -> None:
        """Drop this fan's previous auto post about the same subject.

        Without this, changing your mind stacks contradictory posts — you'd see
        the same fan calling a player a cornerstone AND demanding a trade.
        """
        q = (self.session.query(TeamFeedPost)
             .filter(TeamFeedPost.user_id == userId,
                     TeamFeedPost.is_auto == True,          # noqa: E712
                     TeamFeedPost.target_type == targetType))
        if targetType == 'player':
            q = q.filter(TeamFeedPost.target_player_id == targetPlayerId)
        else:
            q = q.filter(TeamFeedPost.team_id == teamId)
        q.delete(synchronize_session=False)

    def autoPostForRating(self, userId: int, teamId: int, playerId: int,
                          rating: int, rng=None) -> Optional[TeamFeedPost]:
        """Generate the feed post for a player rating.

        A 3 says nothing — a shrug isn't worth a post — and in that case any
        previous auto post is simply withdrawn.
        """
        from constants import FEED_AUTOPOST_BY_RATING
        valence = FEED_AUTOPOST_BY_RATING.get(int(rating))
        self._clearAutoPost(userId, teamId, 'player', playerId)
        if valence is None:
            return None
        return self._addAuto(userId, teamId, 'player', valence, playerId, rng)

    def autoPostForCoachRating(self, userId: int, teamId: int, rating,
                               rng=None) -> Optional[TeamFeedPost]:
        """Generate the feed post for a GM rating.

        Uses the SAME rating->flavour mapping as players, so a 3 says nothing
        about a GM just as it says nothing about a player. `rating=None` means
        the rating was withdrawn, which just clears the post.
        """
        from constants import FEED_AUTOPOST_BY_RATING
        self._clearAutoPost(userId, teamId, 'gm')
        if rating is None:
            return None
        valence = FEED_AUTOPOST_BY_RATING.get(int(rating))
        if valence is None:
            return None
        return self._addAuto(userId, teamId, 'gm', valence, None, rng)

    def _addAuto(self, userId: int, teamId: int, targetType: str, valence: int,
                 targetPlayerId, rng=None) -> TeamFeedPost:
        """Pick a line of the right flavour and post it.

        Randomised across the matching lines so a wave of likes reads as a crowd
        with its own voices rather than the same sentence repeated.
        """
        import random as _random
        choices = [k for k, (_t, tgt, val) in FEED_POST_CATALOG.items()
                   if tgt == targetType and val == valence]
        picker = rng or _random
        key = picker.choice(sorted(choices))
        post = TeamFeedPost(
            user_id=userId, team_id=teamId, post_key=key,
            target_type=targetType, target_player_id=targetPlayerId,
            created_at=self.now(), is_auto=True)
        self.session.add(post)
        return post
