import random

# ── Reaction text pools ──────────────────────────────────────────────────────
# Organized by demeanor → sentiment → list of template strings.
# Templates use {name} for the player's name.

REACTIONS = {
    'stoic': {
        'positive': [
            '{name} blinks. That\'s it. That\'s the celebration.',
            '{name} hands the ball to the ref like they\'re returning a library book.',
            '{name} has not changed facial expression since the coin toss.',
            '{name} nods once. Scientists will debate whether it was intentional.',
            '{name} exhales through their nose. For {name}, this is basically a backflip.',
            '{name} stands motionless while teammates mob them. They are a statue being hugged.',
            '{name} claps once. The sound echoes. Several teammates look concerned.',
            '{name} walks to the sideline at the exact same pace they walked onto the field.',
            '{name} is asked how they feel. They stare at the reporter for four seconds and walk away.',
            '{name} adjusts their wristband. Analysts will call this "electric body language."',
            '{name} makes eye contact with the camera. The camera looks away first.',
            '{name} gives a thumbs-up so minimal it could be a muscle spasm.',
            '{name}\'s heart rate has not changed. The medical staff has checked twice to confirm.',
            '{name} acknowledges the screaming fans with a single, barely perceptible head nod.',
            '{name} places the ball on the turf with the tenderness of a man who will never love again.',
            '{name} sits on the bench. Folds their towel. Stares forward. The void stares back.',
        ],
        'negative': [
            '{name} processes the mistake internally. No one will ever know what that looked like.',
            '{name} blinks twice. For {name}, this is a full emotional breakdown.',
            '{name} stares at the spot where the play happened like they\'re solving a crime.',
            '{name} walks to the sideline at the exact same pace. Always the exact same pace.',
            '{name} sits down. Picks up a water bottle. Puts it down. That was the whole grieving process.',
            '{name} has the same expression they had during warmups, during the national anthem, and during birth.',
            '{name} exhales slightly longer than usual. A teammate asks if they\'re okay. They don\'t respond.',
            '{name} adjusts their gloves. Then their wristband. Then their gloves again. This is coping.',
            '{name} makes eye contact with the coach. The coach sees nothing. There is nothing to see.',
            '{name} picks a blade of grass off their jersey with surgical precision. The crisis has been handled.',
            '{name} sits at the end of the bench. Their face could be on a passport photo right now.',
            '{name} folds their towel into a perfect rectangle. Unfolds it. Folds it again. Healing.',
            '{name} stares at the scoreboard the way most people stare at a wall. Which is also how they stare at walls.',
            '{name} rolls their neck. One crack. That was the tantrum.',
            '{name} puts their hands on their hips for exactly one second, then drops them. Composure restored.',
            '{name} has been sitting in the same position for three minutes. Someone should check on them. But also, this is normal.',
        ],
    },
    'fiery': {
        'positive': [
            '{name} headbutts a teammate so hard both of their helmets crack. They are both thrilled about this.',
            '{name} screams directly into a camera lens. The cameraman will need a moment.',
            '{name} picks up a lineman and carries them. The lineman weighs 310 pounds. {name} does not care.',
            '{name} is chest-bumping people who did not consent to being chest-bumped.',
            '{name} flexes at the {oppTeam} sideline so aggressively a coach drops their clipboard.',
            '{name} grabs two teammates by the facemask and screams "LET\'S GO" from two inches away.',
            '{name} punts a cooler into the second row. Gatorade everywhere. They have never been happier.',
            '{name} is sprinting laps around the endzone. Nobody asked them to do this.',
            '{name} headbutts the goalpost. The goalpost vibrates. {name} does not.',
            '{name} rips a phone book in half on the sideline. Where did they get a phone book?',
            '{name} is screaming the entire playbook from memory while running to the bench.',
            '{name} body-slams the turf so hard the impact shows up on a seismograph.',
            '{name} bear-hugs the referee. The referee is deeply uncomfortable.',
            '{name} dropkicks their own helmet into the stands. They will regret this later.',
            '{name} is doing a war dance that has never been seen in any culture, anywhere, ever.',
            '{name} slaps the {oppTeam} logo at midfield. Repeatedly. While screaming.',
        ],
        'negative': [
            '{name} throws their mouthguard into orbit. It will not be found.',
            '{name} kicks a Gatorade cooler so hard it explodes. The sideline looks like a crime scene.',
            '{name} is arguing with a sideline marker. The marker is inanimate. {name} does not care.',
            '{name} flips a folding chair. Then another one. They are building a folding chair graveyard.',
            '{name} has to be restrained by four coaches and a confused water boy.',
            '{name} is screaming at the sky. A passing bird changes direction.',
            '{name} grabs a towel and wrings it with the intensity of someone disarming a bomb.',
            '{name} headbutts the bench. The bench loses.',
            '{name} is pacing so aggressively they\'re wearing a track into the sideline turf.',
            '{name} yells at a water bottle. The water bottle did nothing wrong.',
            '{name} rips their gloves off and throws them in different directions. Both hit a coach.',
            '{name} is breathing so hard their nostrils are visible from the press box.',
            '{name} punches the air so many times it qualifies as a boxing match.',
            '{name} storms to the sideline. A path clears. People have learned.',
            '{name} screams into their own helmet like a megaphone. It works.',
            '{name} grabs the playsheet, crumples it into a ball, and eats it. Allegedly.',
        ],
    },
    'goofy': {
        'positive': [
            '{name} does the worm for so long the broadcast cuts to commercial and comes back to find them still worming.',
            '{name} moonwalks the entire length of the field. The ref tries to flag it but can\'t stop watching.',
            '{name} finger-guns at every single person in the front row. All of them. It takes a while.',
            '{name} pretends to answer the football like a phone. "Hello? Yes, this is {name}. I\'m kind of busy."',
            '{name} starts a conga line. They are the only person in it. They are having the time of their life.',
            '{name} does a cartwheel so graceful that a gymnastics coach in the stands stands up and applauds.',
            '{name} bowls the football down the sideline and celebrates a strike. It was a gutter ball.',
            '{name} high-fives a ref, a chain gang member, a confused security guard, and someone\'s grandma.',
            '{name} pretends to sign autographs for invisible fans. They\'re taking their time with each one.',
            '{name} pulls an imaginary sword from an imaginary sheath and knights a confused teammate.',
            '{name} does the robot so convincingly that a teammate tries to turn them off.',
            '{name} shoots the football like a three-pointer, yells "KOBE," and it goes directly into a trash can.',
            '{name} starts doing the Macarena. A few fans join in. This is now a movement.',
            '{name} pretends to reel in the football on a fishing line. It\'s a big one. They struggle.',
            '{name} takes a fake selfie with the ref. The ref does not pose. {name} takes another one anyway.',
            '{name} mimes pulling a tablecloth off the field. Everything is still there. Magic.',
        ],
        'negative': [
            '{name} trips over their own feet, does a somersault, and pops up like they meant to do that.',
            '{name} looks at the camera, shrugs, and mouths "these things happen" like a 1950s newsreel.',
            '{name} offers the ball to the {oppTeam} like a gift. "For you. You earned this."',
            '{name} pretends to slip on a banana peel. Then slips for real. Then pretends that was the bit.',
            '{name} does a full theatrical bow, as if the turnover was avant-garde performance art.',
            '{name} mimes rewinding the play like a VCR. Makes the noise and everything. "Can we redo that?"',
            '{name} gives a sheepish thumbs-up from the ground. They are still on the ground.',
            '{name} pretends to file a formal complaint on the sideline. Fills out an imaginary form and everything.',
            '{name} pantomimes crying, then immediately winks at the camera. Unsettling.',
            '{name} does jazz hands at the crowd. The crowd does not know how to respond to this.',
            '{name} points at themselves, mouths "who, me?", then looks behind them like someone else did it.',
            '{name} pretends to call a timeout on themselves. Crosses their arms in a T. The ref is baffled.',
            '{name} laughs so hard at their own mistake they have to sit down.',
            '{name} pulls out an imaginary notepad and pretends to write "do not do that again."',
            '{name} does a pratfall onto the bench so committed that a trainer rushes over.',
            '{name} gives the crowd a beauty pageant wave from the ground. Still down. Still waving.',
        ],
    },
    'dramatic': {
        'positive': [
            '{name} drops to their knees and points to the sky. They are weeping. It\'s the first quarter.',
            '{name} clutches the football like a newborn child and whispers "I will never let you go."',
            '{name} looks directly into the camera and whispers "I told you all. I told every single one of you."',
            '{name} falls backward onto the turf in ecstasy. They stare at the clouds. They see their father.',
            '{name} places both hands on a teammate\'s face and says "we did it" through tears. It\'s week three.',
            '{name} does a slow-motion victory lap. The game is not over. There is an entire quarter left.',
            '{name} sobs into the Gatorade cooler. A trainer pats their back. {name} sobs harder.',
            '{name} raises both arms to the heavens and screams "ARE YOU NOT ENTERTAINED?" It was a 6-yard gain.',
            '{name} cradles the football and sings to it. Nobody knows the song. It might be original.',
            '{name} removes their helmet, lets the wind hit their face, and stares into the distance for 30 seconds.',
            '{name} holds the ball aloft like Simba on Pride Rock. A teammate tries to take it. {name} hisses.',
            '{name} mouths "this is my moment" to nobody, then mouths "this is OUR moment" to everybody.',
            '{name} strikes a Greek statue pose so convincing that a pigeon lands on their shoulder.',
            '{name} slow-motion turns to the crowd with arms outstretched. The broadcast plays it at normal speed. It\'s still slow.',
            '{name} salutes the flag, the crowd, the press box, and a hot dog vendor in section 214.',
            '{name} stands at midfield, arms spread, rain falling on their face. It is not raining.',
        ],
        'negative': [
            '{name} falls to their knees. They stare at their hands. "These hands," they whisper. "These cursed hands."',
            '{name} lies face-down on the turf. A trainer checks on them. They are fine physically. Emotionally? No.',
            '{name} removes their helmet and gazes into the distance like a soldier returning from war.',
            '{name} walks to the bench in slow motion. Nobody else is in slow motion. Just {name}.',
            '{name} collapses onto the bench like a Victorian woman who just received bad news via telegram.',
            '{name} clutches the front of their jersey and staggers sideways. They have not been touched.',
            '{name} reaches one trembling hand toward the scoreboard. "We were so close," they whisper. It\'s 42-10.',
            '{name} rips off their gloves and throws them like they\'re casting aside a former life.',
            '{name} mouths "not like this... not like this" while staring at the ground. A teammate says "dude, it\'s fine."',
            '{name} walks to the tunnel entrance, stops, and turns around for one last look at the field. They are not leaving.',
            '{name} holds their helmet in both hands and stares into the face hole like it\'s a mirror into their soul.',
            '{name} buries their face in a towel. The towel is soaking wet within seconds.',
            '{name} drops to one knee and lowers their head. A coach says "get up." They cannot.',
            '{name} looks up at the sky and mouths "why?" to a god that, in this moment, has no answers.',
            '{name} sits alone at the far end of the bench composing what appears to be a poem.',
            '{name} stares at the football on the ground like it\'s a friend who betrayed them at dinner.',
        ],
    },
    'cool': {
        'positive': [
            '{name} puts on sunglasses. They were already wearing sunglasses. They are now wearing two pairs.',
            '{name} flips the ball over their shoulder without looking. It lands perfectly in the ref\'s hands. The ref is shook.',
            '{name} winks at the camera. Three people watching at home just fell in love.',
            '{name} tosses the ball to the ref. Their hair moves in slow motion. There is no wind.',
            '{name} adjusts their gloves like James Bond adjusting cufflinks before defusing a bomb.',
            '{name} leans against the goalpost with their arms crossed. A photographer wins an award for the shot.',
            '{name} nods at the {oppTeam} bench. Just once. It carries the weight of a thousand words.',
            '{name} does absolutely nothing, and somehow it\'s the coolest thing that\'s happened all game.',
            '{name} blows on their fingertips like a smoking gun. A nearby teammate starts clapping involuntarily.',
            '{name} gives a two-finger salute so smooth that a military official in the stands returns it.',
            '{name} walks off the field. The wind picks up. Their jersey ripples. They did not arrange this.',
            '{name} points at the camera and mouths "you\'re welcome" to the entire viewing audience.',
            '{name} sits down on the bench like they\'re at a five-star restaurant waiting for the wine list.',
            '{name} shoots a look at the camera that makes the commentators forget what they were saying.',
            '{name} smirks. That\'s it. That\'s the whole thing. It was devastating.',
            '{name} gives the crowd the subtlest of nods. 80,000 people feel personally acknowledged.',
        ],
        'negative': [
            '{name} brushes dirt off their shoulder like the play was a minor inconvenience at a gala.',
            '{name} fixes their hair on the way to the sideline. Priorities.',
            '{name} checks their appearance on the jumbotron mid-jog. Adjusts collar. Satisfied.',
            '{name} yawns so theatrically that the {oppTeam} bench takes it personally.',
            '{name} tips an imaginary hat to the defender who just beat them. The defender is confused and flattered.',
            '{name} shrugs with a half-smile that somehow communicates "I am still better than you."',
            '{name} pretends to check a watch they\'re not wearing. "Would you look at the time."',
            '{name} mouths "it happens" with a smirk so confident it borders on delusional.',
            '{name} flicks an invisible speck of dust off their jersey. The jersey is filthy. They don\'t care.',
            '{name} leans back on the bench like they own the stadium and are simply allowing others to use it.',
            '{name} gives a sarcastic slow clap for themselves. It is somehow not embarrassing.',
            '{name} stretches casually, as if the play happened to someone else. Someone less cool.',
            '{name} sits down and crosses their legs on the bench. A teammate has never seen someone sit so hard.',
            '{name} just stares ahead. Unfazed. A glacier has more emotional range.',
            '{name} makes a "not bad" face at the defender. The defender worked very hard on that play.',
            '{name} walks to the sideline like they\'re on a runway. They might actually be on a runway.',
        ],
    },
    'intense': {
        'positive': [
            '{name} rips the tablet out of a coach\'s hands to rewatch the play.',
            '{name} sprints to the whiteboard and starts diagramming.',
            '{name} is screaming about the game plan while teammates are still celebrating.',
            '{name} grabs the film coordinator by the shoulders and demands the All-22.',
            '{name} mutters the play call to themselves seven times in a row.',
            '{name} has memorized every defensive alignment they\'ve seen today. All of them.',
            '{name} is drawing plays on a coach\'s clipboard without asking permission.',
            '{name} did not celebrate. There is no time.',
            '{name} is quizzing a teammate about coverage assignments mid-celebration.',
            '{name} physically drags a coach to the whiteboard to discuss adjustments.',
            '{name} has rewound the tablet replay eleven times. They found something.',
            '{name} mouths the snap count, audibles, and hot routes while walking to the sideline.',
            '{name} has not blinked in forty-five seconds. They are processing.',
            '{name} predicted this exact play in the pregame walkthrough and needs everyone to know.',
            '{name} is holding two tablets at once and comparing frame-by-frame.',
            '{name} taps their temple aggressively. They cracked the code.',
        ],
        'negative': [
            '{name} snatches the tablet and rewinds the play before they even reach the sideline.',
            '{name} has already identified four things that went wrong and is listing them out loud.',
            '{name} corners the coordinator and will not let them leave until they discuss the protection.',
            '{name} is watching the jumbotron replay with the intensity of someone defusing a bomb.',
            '{name} is muttering corrections so fast they sound like an auctioneer.',
            '{name} has filled an entire page of their sideline notebook in thirty seconds.',
            '{name} is recalculating every possible outcome from this drive on the tablet.',
            '{name} is mouthing the entire defensive scheme to themselves like a manifesto.',
            '{name} fast-forwards, rewinds, pauses, rewinds again. They will find the answer.',
            '{name} has already asked three different coaches what went wrong. None of them agree.',
            '{name} is cross-referencing the tablet, the playsheet, AND the whiteboard.',
            '{name} is staring at the field with such intensity the turf might catch fire.',
            '{name} holds up a finger to anyone who tries to talk to them. They need sixty more seconds.',
            '{name} has drawn up seven counter-plays and is ranking them by expected value.',
            '{name} interrogates a teammate: "what did the corner do on the snap? WHAT DID HE DO?"',
            '{name} refuses to acknowledge the play is over until they understand every assignment.',
        ],
    },
    'shy': {
        'positive': [
            '{name} tries to hand the ball to someone else before anyone can congratulate them.',
            '{name} is physically hiding behind a 320-pound lineman. Only their helmet is visible.',
            '{name} sprints to the bench like the endzone is on fire. The celebration is too much.',
            '{name} gives the world\'s smallest fist bump. Contact is made with one knuckle.',
            '{name} turns so red their face is visible through their helmet.',
            '{name} mumbles "thanks" so quietly that a lip-reader on the broadcast can\'t even catch it.',
            '{name} waves off a camera so frantically they almost knock it over.',
            '{name} accepts a high-five but immediately pulls their hand back like they touched a stove.',
            '{name} stares at the ground so hard they might be trying to tunnel through it.',
            '{name} gives the quietest "yeah" in NFL history. Dogs heard it. Humans did not.',
            '{name} is hiding behind the Gatorade table. A trainer asks if they\'re okay. They say nothing.',
            '{name} fidgets with their chinstrap for 45 seconds to avoid looking at literally anyone.',
            '{name} looks like they\'d rather be anywhere else on Earth than in front of 80,000 people right now.',
            '{name} jogs to the sideline so fast it looks like they\'re fleeing a crime scene.',
            '{name} gives a smile so small you need the broadcast zoom to confirm it happened.',
            '{name} is asked for a comment by a sideline reporter. They just shake their head and speed-walk away.',
        ],
        'negative': [
            '{name} pulls their jersey up over their face. They may never come out.',
            '{name} speed-walks to the far end of the bench, past the backup kicker, past the equipment bags, past the state line.',
            '{name} shrinks into their shoulder pads like a turtle retreating into its shell.',
            '{name} puts a towel over their head. They will live here now.',
            '{name} mouths "sorry" to every single person on the sideline individually. This takes a while.',
            '{name} is pretending to be VERY interested in their cleats. Fascinating cleats. Could study them for hours.',
            '{name} hides behind a water jug. The water jug is not large enough to hide behind. They try anyway.',
            '{name} wishes the earth would open up and swallow them. It does not. They must continue being perceived.',
            '{name} sits at the very end of the bench, past where the bench ends, technically sitting on air.',
            '{name} says "my bad" so softly that a butterfly three feet away did not hear it.',
            '{name} turns their back to the camera. Then turns their back to the sideline. They are now facing a wall.',
            '{name} is trying to physically merge with the bench. Molecular science says no. They keep trying.',
            '{name} avoids eye contact with the coaching staff, the players, the fans, and a bird.',
            '{name} is sitting so still they\'ve been mistaken for equipment twice.',
            '{name} makes themselves as small as possible. For a professional athlete, this is still pretty big.',
            '{name} stares at their shoes with such intensity they might be reading something written on them.',
        ],
    },
    'melancholy': {
        'positive': [
            '{name} smiles, but it doesn\'t quite reach their eyes.',
            '{name} stares down the field like it reminds them of something.',
            '{name} sighs contentedly, as if this moment won\'t last.',
            '{name} looks at the sky with a bittersweet expression.',
            '{name} whispers "at least there\'s this" to no one.',
            '{name} holds the football for a moment too long before letting go.',
            '{name} savors the moment, knowing it\'s fleeting.',
            '{name} nods slowly, as if remembering why they play.',
            '{name} closes their eyes for a moment on the sideline.',
            '{name} looks at the crowd with a gentle, faraway expression.',
            '{name} pats the ball twice before handing it off. Saying goodbye.',
            '{name} watches the replay like it\'s a memory that\'s already fading.',
            '{name} takes a slow, deep breath and holds it.',
            '{name} sits on the bench and just... looks at the field.',
            '{name} smiles at a teammate in a way that seems heavy.',
            '{name} whispers "this is why" to themselves.',
        ],
        'negative': [
            '{name} stares into the middle distance.',
            '{name} sits alone on the bench, lost in thought.',
            '{name} looks at the rain like it understands them.',
            '{name} sighs deeply, as if they expected this.',
            '{name} gazes at the scoreboard with quiet resignation.',
            '{name} pulls their towel over their head and goes somewhere far away.',
            '{name} whispers "it\'s fine" in a way that suggests it is not fine.',
            '{name} watches the replay with the expression of someone reading old letters.',
            '{name} closes their eyes and listens to the crowd noise fade.',
            '{name} traces a line on the bench with their finger.',
            '{name} looks at the empty seats in the upper deck.',
            '{name} hums something under their breath. Something sad.',
            '{name} holds the towel but doesn\'t wipe anything. Just holds it.',
            '{name} stares at the field like it\'s an old friend who let them down.',
            '{name} sits perfectly still, weathering something internal.',
            '{name} whispers "of course" with the weight of someone who\'s been here before.',
        ],
    },
    'rude': {
        'positive': [
            '{name} pretends to use the football as a phone and calls the {oppTeam}\'s coach.',
            '{name} blows a kiss to the {oppTeam} fans.',
            '{name} waves goodbye to the defender they just burned.',
            '{name} mouths "scoreboard" at the {oppTeam} bench.',
            '{name} wags their finger at the defense like a disapproving teacher.',
            '{name} cups their ear toward the now-silent {oppTeam} fans.',
            '{name} pretends to tuck the defender into bed.',
            '{name} walks backward toward the sideline, maintaining eye contact with the defense.',
            '{name} does the "too small" gesture at the defender.',
            '{name} pantomimes writing a receipt for the defender.',
            '{name} blows on the defender like they\'re a dandelion.',
            '{name} waves at the {oppTeam} coach with a big grin.',
            '{name} points at the scoreboard and then at themselves.',
            '{name} shushes the {oppTeam} sideline.',
            '{name} air-mails a kiss to the {oppTeam}\'s mascot.',
            '{name} pretends to read a newspaper on the sideline.',
        ],
        'negative': [
            '{name} kicks a water bottle and then blames the water bottle.',
            '{name} sits down and criticizes the stadium\'s Wi-Fi.',
            '{name} blames the turf.',
            '{name} mutters something about the weather.',
            '{name} complains that the bench is uncomfortable.',
            '{name} tells no one in particular "this is what I was talking about."',
            '{name} shakes their head like a disappointed parent.',
            '{name} sighs loud enough for three zip codes to hear.',
            '{name} loudly blames the play call.',
            '{name} asks the sideline "does ANYONE know what they\'re doing?"',
            '{name} rolls their eyes at the replay.',
            '{name} mutters "unbelievable" while looking at a teammate.',
            '{name} complains about the stadium lights to a trainer.',
            '{name} side-eyes the coaching staff on the way to the bench.',
            '{name} tells the water table it\'s in the wrong spot.',
            '{name} glares at the crowd like they caused this.',
        ],
    },
    'wholesome': {
        'positive': [
            '{name} immediately hugs the nearest teammate.',
            '{name} points to the offensive line and claps for them.',
            '{name} runs to the sideline and high-fives every single person.',
            '{name} thanks the ref for a good game so far.',
            '{name} finds the backup and tells them "we did this together."',
            '{name} blows a kiss to their family in the stands.',
            '{name} gives the ball to a kid in the front row.',
            '{name} tells the {oppTeam} players "great effort out there."',
            '{name} helps a {oppTeam} player off the ground before celebrating.',
            '{name} looks for the teammate who made the key block and points at them.',
            '{name} puts an arm around a rookie on the sideline.',
            '{name} mouths "I love this team" to the camera.',
            '{name} claps for the crowd and bows.',
            '{name} gives the water boy a fist bump.',
            '{name} tells a coach "that play was all you."',
            '{name} is beaming. So wholesome.',
        ],
        'negative': [
            '{name} pats the defender on the back and says "good play."',
            '{name} apologizes to a teammate for letting them down.',
            '{name} jogs off encouraging everyone else to keep their heads up.',
            '{name} tells the coach "I\'ll do better next time, I promise."',
            '{name} gives a thumbs-up to the crowd to say "I\'m okay."',
            '{name} is consoling a teammate who had nothing to do with the play.',
            '{name} mouths "it\'s my fault" and takes full responsibility.',
            '{name} shakes a {oppTeam} player\'s hand.',
            '{name} checks on a teammate before heading to the sideline.',
            '{name} tells the coach "put me back in, I\'ll fix it."',
            '{name} pats themselves on the helmet as if to say "shake it off."',
            '{name} gives the defense credit on the way to the bench.',
            '{name} picks up a teammate\'s towel and hands it back.',
            '{name} tells a younger player "I\'ve been there. You\'ll bounce back."',
            '{name} is the first to clap after a {oppTeam} good play.',
            '{name} sits down and immediately asks how everyone else is doing.',
        ],
    },
    'paranoid': {
        'positive': [
            '{name} whispers to a teammate "Act casual. We don\'t want to tip them off that we know."',
            '{name} points at the refs like "I know what you almost did."',
            '{name} celebrates but keeps scanning the crowd. Someone is watching.',
            '{name} mutters "they\'re gonna try to take this from us. They always do."',
            '{name} scans the stadium exits during the celebration. Just in case.',
            '{name} says "that play worked DESPITE everything working against us."',
            '{name} tells a coach "we need to check the game balls. Something felt off."',
            '{name} looks over both shoulders mid-celebration. Then checks again.',
            '{name} tells a teammate "don\'t celebrate too loud. That\'s how they get you."',
            '{name} whispers "they didn\'t think we\'d figure it out. But we did."',
            '{name} eyes the chain gang like they\'re in on something.',
            '{name} is certain the stadium lights flickered on purpose during the play.',
            '{name} checks the play clock, the game clock, and their own watch. Something doesn\'t add up.',
            '{name} celebrates facing the press box so they can\'t photograph the playsheet.',
            '{name} tells the QB "change the audible. The hot dog guy is acting suspicious."',
            '{name} asks a teammate "did you feel that? The turf is different on this side of the field."',
        ],
        'negative': [
            '{name} covers their mouth while talking to a coach. The cameras are always watching.',
            '{name} is telling anyone who\'ll listen that the field was measured wrong.',
            '{name} looks directly into the camera. They know exactly who\'s on the other end.',
            '{name} whispers to a teammate "the mascot has been following me all game."',
            '{name} asks the equipment manager to check the helmet for tracking devices.',
            '{name} notices a bird flying overhead and does not think it\'s a coincidence.',
            '{name} tells the coach "they cracked the code, I know they did."',
            '{name} is writing something down in a notebook they won\'t let anyone else see.',
            '{name} checks under the bench. Then checks again.',
            '{name} tells a teammate "the announcer said my name weird. They\'re trying to get in my head."',
            '{name} is certain the jumbotron showed the replay at the wrong speed to mess with them.',
            '{name} asks the trainer if the water tastes different today. It tastes different.',
            '{name} refuses to discuss the play. Not here. Not where they can hear.',
            '{name} squints at a janitor in the tunnel. "Since when do we have a janitor?"',
            '{name} is counting the people in the press box. There\'s one more than last time.',
            '{name} tells a coach "I\'m not saying it\'s a conspiracy, but I\'m not NOT saying that."',
        ],
    },
    'enigmatic': {
        'positive': [
            '{name} whispers a secret to the football before handing it to the ref.',
            '{name} stares directly at the sun for an amount of time that concerns the medical staff.',
            '{name} traces an elaborate symbol on the turf. A teammate asks what it means. {name} says "not yet."',
            '{name} gives a thumbs-up to an empty section of the stadium. Holds it there.',
            '{name} stands perfectly still, facing the wrong direction.',
            '{name} bows deeply to the goalpost. The goalpost does not respond.',
            '{name} holds up three fingers. No one knows what it means. {name} won\'t explain.',
            '{name} looks at the crowd and slowly nods, as if confirming something they already knew.',
            '{name} places the ball on a very specific blade of grass. Adjusts it twice.',
            '{name} says a single word no one understands. Says it again. Walks away satisfied.',
            '{name} closes their eyes and holds their palms up to the sky. A teammate asks if they\'re okay. They don\'t answer.',
            '{name} tilts their head at the scoreboard like it just told them something personal.',
            '{name} picks up a handful of turf and lets it fall through their fingers like sand.',
            '{name} walks in a perfect circle three times before returning to the sideline.',
            '{name} looks at a cloud and whispers "thank you."',
            '{name} hands the ref the ball and says "it remembers." The ref has no idea what to do with that.',
        ],
        'negative': [
            '{name} laughs to themselves. They don\'t stop for a while.',
            '{name} just nods. This was always going to happen. They saw it in a dream.',
            '{name} picks up a blade of grass, smells it, and puts it in their pocket.',
            '{name} stares at their own hands like they belong to someone else.',
            '{name} whispers "interesting" and walks away. No one knows what was interesting.',
            '{name} sits cross-legged on the 40-yard line. A coach asks them to move. They don\'t.',
            '{name} points at something in the sky. There is nothing in the sky.',
            '{name} smiles. It\'s the kind of smile that makes a teammate change seats on the bench.',
            '{name} touches the goalpost on the way off the field and says "soon."',
            '{name} looks at the ref and says "you feel it too, don\'t you?"',
            '{name} draws something in the dirt with their toe. A teammate glances at it. {name} erases it immediately.',
            '{name} closes their eyes on the sideline and begins humming a tune nobody recognizes.',
            '{name} picks up the ball, holds it to their ear, frowns, then puts it down gently.',
            '{name} reads the yard marker number out loud. Twice. Writes it on their wrist.',
            '{name} walks to the bench in a spiral pattern. No one says anything.',
            '{name} stares at the back of their own hand for thirty seconds. Turns it over. Stares at the other side.',
        ],
    },
    'superstitious': {
        'positive': [
            '{name} taps the goalpost three times, pauses, then taps it four more times because three felt wrong.',
            '{name} credits the play entirely to the fact that they ate exactly 11 grapes at breakfast.',
            '{name} whispers "I told you" to a penny they found in the parking lot this morning.',
            '{name} kisses each finger individually, touches the turf, spins counterclockwise, and exhales through the left nostril only.',
            '{name} confirms to a coach that this happened because they parked in the same spot as last week.',
            '{name} is already planning to wear the exact same underwear next week.',
            '{name} nods at a specific section of the crowd. Their lucky stranger is out there somewhere.',
            '{name} refuses to high-five with their left hand. Not after what happened.',
            '{name} touches the sideline with their right foot, then left, then right again. Always right, then left, then right.',
            '{name} is thanking the pre-game playlist. Specifically track seven. Track seven always delivers.',
            '{name} makes a teammate walk back and re-enter the sideline from the correct end. It matters.',
            '{name} looks at the sky. The clouds are in the right shape today.',
            '{name} demands to know the exact temperature. It needs to match their jersey number or this means nothing.',
            '{name} tied their cleats using the special knot. The special knot has never lost.',
            '{name} will not discuss the play until they\'ve touched the bench with both hands. Now they can talk.',
            '{name} steps over the sideline chalk with their right foot. Always right. The one time they went left they tore an ACL.',
        ],
        'negative': [
            '{name} realizes with horror that they put their left cleat on before their right today.',
            '{name} is blaming this entirely on the equipment manager who washed their lucky towel.',
            '{name} knew this would happen. They saw a bird on the way to the stadium. A bird.',
            '{name} is checking if Mercury is in retrograde on the sideline tablet. The trainer says no. {name} doesn\'t believe them.',
            '{name} whispers a lengthy apology to the penny in their locker. They have failed it.',
            '{name} is re-tying their cleats in the sacred order: right over left, loop twice, tuck, pull. They must have rushed it.',
            '{name} demands to know who touched their helmet. Someone moved it. They can tell.',
            '{name} refuses to step on yard lines walking back to the sideline. It takes them twice as long to get there.',
            '{name} is convinced this happened because a teammate changed their pre-game handshake without warning.',
            '{name} touches the bench three times, sits, stands, touches it three more times. The first three didn\'t feel right.',
            '{name} is mentally cataloging every deviation from routine today. The list is already too long.',
            '{name} asks a coach what song was playing in the tunnel. A different song was playing. That explains everything.',
            '{name} blames a teammate who walked under a ladder in the facility three days ago. "I said something. I SAID something."',
            '{name} is staring at the scoreboard. The numbers are bad. They\'re all bad.',
            '{name} will not sit in the same seat they were in earlier. That seat is cursed now.',
            '{name} is quietly counting the lights in the stadium. If it\'s an even number, they can recover from this.',
        ],
    },
    'oblivious': {
        'positive': [
            '{name} looks around pleasantly, completely unaware they were involved in the play.',
            '{name} hands the ball to the ref with a polite "here you are" and a little bow.',
            '{name} gets up off the turf, notices something on the ground, and picks it up. It\'s a piece of tape. They pocket it.',
            '{name} smiles and waves at the crowd. The crowd is not looking at them. They keep waving.',
            '{name} is standing on the field staring at a bird. The huddle is forming without them.',
            '{name} gives the ball to a kid in the stands. It is the game ball. A coach has to go get it back.',
            '{name} is standing perfectly still on the field. A teammate asks if they\'re coming. "Where?" says {name}.',
            '{name} has found a ladybug on their glove and is showing it to the nearest person, who is a {oppTeam} linebacker.',
            '{name} pats the defender on the back and says "great job out there." The defender is very confused.',
            '{name} is applauding. It\'s unclear what for. They seem genuinely delighted.',
            '{name} gets up and starts walking toward the wrong huddle. Gets redirected. Wanders back.',
            '{name} tries to hand the ball to a teammate. The teammate does not need the ball. {name} insists.',
            '{name} is looking at their own hands with quiet wonder, as if seeing them for the first time.',
            '{name} gets up, dusts off their jersey, and walks confidently in the wrong direction.',
            '{name} gives a thumbs-up to absolutely no one. Holds it there. Seems satisfied.',
            '{name} stands up after the play and adjusts their helmet. It\'s on backward. They don\'t notice.',
        ],
        'negative': [
            '{name} looks around with mild curiosity, as if something just happened nearby but they\'re not sure what.',
            '{name} gets up off the turf looking genuinely surprised to be on the ground.',
            '{name} is trying to put their mouthguard back in upside down. It\'s not going well but they\'re committed.',
            '{name} looks at the ref expectantly, like a dog waiting for a treat.',
            '{name} picks themselves up, brushes off their jersey, and compliments the defender on their outfit.',
            '{name} is standing in the wrong spot. A teammate moves them. They drift back.',
            '{name} tries to hand the ball to the {oppTeam}. Helpfully.',
            '{name} gets up and walks toward the wrong sideline. A {oppTeam} coach gently redirects them.',
            '{name} is looking at the sky. Something up there is very interesting to them. No one else sees it.',
            '{name} has their gloves on the wrong hands. A teammate points this out. {name} looks at both hands for a very long time.',
            '{name} nods thoughtfully at the ref, as if they understood the call.',
            '{name} gets up, pats the defender who just tackled them, and says "nice to meet you."',
            '{name} walks into a teammate while looking the other direction. Apologizes to the wrong person.',
            '{name} is trying to figure out which direction they\'re supposed to be going. Points one way. Then the other.',
            '{name} picks up the ball and offers it to the nearest person like a gift.',
            '{name} is explaining something to a teammate using hand gestures that clarify absolutely nothing.',
        ],
    },
}


def generateReaction(playerName, teamAbbr, demeanor, isPositive, oppTeamName=''):
    """Generate a reaction dict for a highlight play.

    Args:
        playerName: Display name of the reacting player
        teamAbbr: Team abbreviation
        demeanor: One of the demeanor types
        isPositive: True for positive plays, False for negative
        oppTeamName: Name of the opposing team

    Returns:
        dict with type, text, playerName, teamAbbr, demeanor, sentiment
    """
    sentiment = 'positive' if isPositive else 'negative'
    pool = REACTIONS.get(demeanor, REACTIONS['stoic']).get(sentiment, [])
    if not pool:
        return None

    template = random.choice(pool)
    text = template.format(name=playerName, oppTeam=oppTeamName or 'the other team')

    return {
        'type': 'reaction',
        'text': text,
        'playerName': playerName,
        'teamAbbr': teamAbbr,
        'demeanor': demeanor,
        'sentiment': sentiment,
    }
