"""Initial schema

Revision ID: 3e9627549a3b
Revises: 
Create Date: 2026-02-11 17:51:14.231767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e9627549a3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('unused_names',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('abbr', sa.String(length=10), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('offense_rating', sa.Integer(), nullable=False),
    sa.Column('defense_rating', sa.Integer(), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('gm_score', sa.Integer(), nullable=True),
    sa.Column('defense_tier', sa.Integer(), nullable=True),
    sa.Column('defense_run_coverage_rating', sa.Integer(), nullable=True),
    sa.Column('defense_pass_coverage_rating', sa.Integer(), nullable=True),
    sa.Column('defense_pass_rush_rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbr')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('home_score_q1', sa.Integer(), nullable=False),
    sa.Column('home_score_q2', sa.Integer(), nullable=False),
    sa.Column('home_score_q3', sa.Integer(), nullable=False),
    sa.Column('home_score_q4', sa.Integer(), nullable=False),
    sa.Column('home_score_ot', sa.Integer(), nullable=False),
    sa.Column('away_score_q1', sa.Integer(), nullable=False),
    sa.Column('away_score_q2', sa.Integer(), nullable=False),
    sa.Column('away_score_q3', sa.Integer(), nullable=False),
    sa.Column('away_score_q4', sa.Integer(), nullable=False),
    sa.Column('away_score_ot', sa.Integer(), nullable=False),
    sa.Column('is_overtime', sa.Boolean(), nullable=False),
    sa.Column('current_quarter', sa.Integer(), nullable=False),
    sa.Column('total_plays', sa.Integer(), nullable=True),
    sa.Column('game_date', sa.DateTime(), nullable=True),
    sa.Column('is_playoff', sa.Boolean(), nullable=False),
    sa.Column('playoff_round', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_games_away_team', 'games', ['away_team_id'], unique=False)
    op.create_index('idx_games_home_team', 'games', ['home_team_id'], unique=False)
    op.create_index('idx_games_season_week', 'games', ['season', 'week'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('current_number', sa.Integer(), nullable=True),
    sa.Column('preferred_number', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('seasons_played', sa.Integer(), nullable=False),
    sa.Column('term', sa.Integer(), nullable=True),
    sa.Column('term_remaining', sa.Integer(), nullable=True),
    sa.Column('cap_hit', sa.Integer(), nullable=True),
    sa.Column('player_rating', sa.Integer(), nullable=True),
    sa.Column('free_agent_years', sa.Integer(), nullable=True),
    sa.Column('service_time', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_players_position', 'players', ['position'], unique=False)
    op.create_index('idx_players_team', 'players', ['team_id'], unique=False)
    op.create_table('seasons',
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('current_week', sa.Integer(), nullable=False),
    sa.Column('playoffs_started', sa.Boolean(), nullable=False),
    sa.Column('champion_team_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['champion_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('season_number')
    )
    op.create_table('team_season_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('elo', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('win_percentage', sa.Float(), nullable=True),
    sa.Column('streak', sa.Integer(), nullable=True),
    sa.Column('score_differential', sa.Integer(), nullable=True),
    sa.Column('made_playoffs', sa.Boolean(), nullable=False),
    sa.Column('league_champion', sa.Boolean(), nullable=False),
    sa.Column('floosball_champion', sa.Boolean(), nullable=False),
    sa.Column('top_seed', sa.Boolean(), nullable=False),
    sa.Column('offense_stats', sa.JSON(), nullable=True),
    sa.Column('defense_stats', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'season', name='uq_team_season')
    )
    op.create_index('idx_team_stats_season', 'team_season_stats', ['season'], unique=False)
    op.create_index('idx_team_stats_team', 'team_season_stats', ['team_id'], unique=False)
    op.create_table('game_player_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('passing_stats', sa.JSON(), nullable=True),
    sa.Column('rushing_stats', sa.JSON(), nullable=True),
    sa.Column('receiving_stats', sa.JSON(), nullable=True),
    sa.Column('kicking_stats', sa.JSON(), nullable=True),
    sa.Column('defense_stats', sa.JSON(), nullable=True),
    sa.Column('fantasy_points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', name='uq_game_player')
    )
    op.create_index('idx_game_stats_game', 'game_player_stats', ['game_id'], unique=False)
    op.create_index('idx_game_stats_player', 'game_player_stats', ['player_id'], unique=False)
    op.create_table('player_attributes',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('hands', sa.Integer(), nullable=False),
    sa.Column('agility', sa.Integer(), nullable=False),
    sa.Column('power', sa.Integer(), nullable=False),
    sa.Column('arm_strength', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Integer(), nullable=False),
    sa.Column('leg_strength', sa.Integer(), nullable=False),
    sa.Column('skill_rating', sa.Integer(), nullable=False),
    sa.Column('potential_speed', sa.Integer(), nullable=False),
    sa.Column('potential_hands', sa.Integer(), nullable=False),
    sa.Column('potential_agility', sa.Integer(), nullable=False),
    sa.Column('potential_power', sa.Integer(), nullable=False),
    sa.Column('potential_arm_strength', sa.Integer(), nullable=False),
    sa.Column('potential_accuracy', sa.Integer(), nullable=False),
    sa.Column('potential_leg_strength', sa.Integer(), nullable=False),
    sa.Column('potential_skill_rating', sa.Integer(), nullable=False),
    sa.Column('route_running', sa.Integer(), nullable=False),
    sa.Column('vision', sa.Integer(), nullable=False),
    sa.Column('blocking', sa.Integer(), nullable=False),
    sa.Column('discipline', sa.Integer(), nullable=False),
    sa.Column('attitude', sa.Integer(), nullable=False),
    sa.Column('focus', sa.Integer(), nullable=False),
    sa.Column('instinct', sa.Integer(), nullable=False),
    sa.Column('creativity', sa.Integer(), nullable=False),
    sa.Column('resilience', sa.Integer(), nullable=False),
    sa.Column('clutch_factor', sa.Integer(), nullable=False),
    sa.Column('pressure_handling', sa.Integer(), nullable=False),
    sa.Column('longevity', sa.Integer(), nullable=False),
    sa.Column('play_making_ability', sa.Integer(), nullable=False),
    sa.Column('x_factor', sa.Integer(), nullable=False),
    sa.Column('confidence_modifier', sa.Integer(), nullable=False),
    sa.Column('determination_modifier', sa.Integer(), nullable=False),
    sa.Column('luck_modifier', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('player_career_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('fantasy_points', sa.Integer(), nullable=False),
    sa.Column('passing_stats', sa.JSON(), nullable=True),
    sa.Column('rushing_stats', sa.JSON(), nullable=True),
    sa.Column('receiving_stats', sa.JSON(), nullable=True),
    sa.Column('kicking_stats', sa.JSON(), nullable=True),
    sa.Column('defense_stats', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', name='uq_player_season')
    )
    op.create_index('idx_career_stats_player', 'player_career_stats', ['player_id'], unique=False)
    op.create_index('idx_career_stats_season', 'player_career_stats', ['season'], unique=False)
    op.create_table('records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_type', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('stat_name', sa.String(length=50), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_records_category', 'records', ['category', 'subcategory', 'scope'], unique=False)
    op.create_index('idx_records_type', 'records', ['record_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_records_type', table_name='records')
    op.drop_index('idx_records_category', table_name='records')
    op.drop_table('records')
    op.drop_index('idx_career_stats_season', table_name='player_career_stats')
    op.drop_index('idx_career_stats_player', table_name='player_career_stats')
    op.drop_table('player_career_stats')
    op.drop_table('player_attributes')
    op.drop_index('idx_game_stats_player', table_name='game_player_stats')
    op.drop_index('idx_game_stats_game', table_name='game_player_stats')
    op.drop_table('game_player_stats')
    op.drop_index('idx_team_stats_team', table_name='team_season_stats')
    op.drop_index('idx_team_stats_season', table_name='team_season_stats')
    op.drop_table('team_season_stats')
    op.drop_table('seasons')
    op.drop_index('idx_players_team', table_name='players')
    op.drop_index('idx_players_position', table_name='players')
    op.drop_table('players')
    op.drop_index('idx_games_season_week', table_name='games')
    op.drop_index('idx_games_home_team', table_name='games')
    op.drop_index('idx_games_away_team', table_name='games')
    op.drop_table('games')
    op.drop_table('teams')
    op.drop_table('unused_names')
    op.drop_table('leagues')
    # ### end Alembic commands ###
