"""Add team historical stats fields

Revision ID: b7d61db061a8
Revises: 3e9627549a3b
Create Date: 2026-02-11 18:33:32.791164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d61db061a8'
down_revision: Union[str, Sequence[str], None] = '3e9627549a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('defense_season_performance', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('all_time_stats', sa.JSON(), nullable=True))
    op.add_column('teams', sa.Column('league_championships', sa.JSON(), nullable=True))
    op.add_column('teams', sa.Column('floosbowl_championships', sa.JSON(), nullable=True))
    op.add_column('teams', sa.Column('regular_season_champions', sa.JSON(), nullable=True))
    op.add_column('teams', sa.Column('playoff_appearances', sa.JSON(), nullable=True))
    op.add_column('teams', sa.Column('roster_history', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'roster_history')
    op.drop_column('teams', 'playoff_appearances')
    op.drop_column('teams', 'regular_season_champions')
    op.drop_column('teams', 'floosbowl_championships')
    op.drop_column('teams', 'league_championships')
    op.drop_column('teams', 'all_time_stats')
    op.drop_column('teams', 'defense_season_performance')
    # ### end Alembic commands ###
